### ISSUE TITLE
Use PostGIS to store lat/long

### ISSUE THREAD

**Issue by kriegfrj** [bxservice/de.bxservice.georeferencing#2]
It would be nice if the lat/long were encoded as a PostGIS Point so that you could do spatial SQL queries - eg, you could have a particular marketing region defined as a geometry and stored in the db, then show all customers in that region.

Perhaps this would be an extra plugin rather than part of the base plugin - I know that this would be Postgres-specific.

**Comment by CarlosRuiz-globalqss** [comment]
it is a good idea, but we don't want to make the plugin dependent on a specific postgresql extension

googling - it seems this can be achieved easily still using the lat/lon coordinates:
https://gis.stackexchange.com/questions/145007/creating-geometry-from-lat-lon-in-table-using-postgis
